---
layout: post  
title: "Java-13 (Exception)"  
categories: java
---

## Exception

- 예상치 못한 문제가 생기는 경우 발생하는 이벤트
- 예외처리로 비지니스에 집중 할 수 있음.

<br/>

### try-catch 

```java
import java.util.List;
import java.util.Arrays;

public class Application {
    public static void main(String args[]) {
        process();
    }
    
    public static void process() {
        List<String> data = getData();
        if (data == null || data.isEmpty()) {
            System.out.println("empty!");
            return;
        }
        
        if (data.size() < 3) {
            System.out.println("invalid data!");
            return;
        }
            
        System.out.println(data.get(2));
    }
    
    public static List<String> getData() {
        return Arrays.asList("A", "B", "C");
    }
}
```
```java
import java.util.List;
import java.util.Arrays;

public class Application {
    public static void main(String args[]) {
        try {
            process();
        } catch (NullPointerException e) {
            System.out.println("empty!");
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("invalid data!");
        }
    }
    
    public static void process() {
        List<String> data = getData();
        System.out.println(data.get(2));
    }
    
    public static List<String> getData() {
        return Arrays.asList("A", "B", "C");
    }
}
```

<br/>

### try-catch-finally

- finally 구문은 무조건 try-catch 이후 무조건 수행 된다.

```java
import java.util.List;
import java.util.Arrays;

public class MyClass {
    public static void main(String args[]) {
        FileService fs = new FileService();
        try {
            fs.open();
            fs.access();
        } catch (Exception e) {
            System.out.println("err!");
        } finally {
            fs.close();
        }
    }
    
    public static class FileService {
        public void open() {
            System.out.println("open");
        }
        
        public void close() {
            System.out.println("close");
        }
        
        public void access() {
            throw new IllegalArgumentException();
        }
    }
}
```
```
open
err!
close
```

<br/>

### try-resource

- 자바 7 이후 버전에서 사용 가능.
- java.lang.AutoCloseable 구현한 객체들로 한하여 자동으로 자원을 반환 할 수 있음. 

```java
import java.io.BufferedReader;
import java.io.FileReader;

public class Application {
    public static void main(String args[]) {
        String line = null;
        try(BufferedReader in = new BufferedReader(new FileReader("test.txt"))) {
            while((line = in.readLine()) != null) {
                System.out.println(line);
            }
        } catch (Exception e) {
            System.out.println("ERR!");
        }
    }
}
```

<br/>

### Checked Exception, Unchecked Exception

- Unchecked Exception은 RuntimeException을 상속한다. 
- checked Exception은 RuntimeException을 상속하지 않는다.
- 메소드를 호출한 곳에서 에러를 다룰 수 있다면 checked, 아니면 unchecked 던지도록 개발.  

| |checked Exception|Unchecked Exception|
|---|---|---|
|처리여부|반드시 예외 처리|예외 처리 안해도 됨|
|트랜잭션처리|roll-back 안함|roll-back 처리|
|ex|IOException|NullPointerException|
 